# Generated by Django 5.1.3 on 2024-11-23 08:36

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150, verbose_name='site name')),
                ('phone_no', models.CharField(max_length=50, validators=[about.models.validate_nepali_phone_number], verbose_name='Phone Number(contact no)')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Upload logo')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Facebook Link')),
                ('insta_link', models.URLField(blank=True, null=True, verbose_name='Instagram Link')),
                ('linkedIn_link', models.URLField(blank=True, null=True, verbose_name='LinkedIn Link')),
                ('whatsapp_link', models.URLField(verbose_name='whatsapp')),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
            },
        ),
    ]
