# Generated by Django 5.1.3 on 2024-11-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True, verbose_name='whatsapp'),
        ),
    ]
