# Generated by Django 5.1.3 on 2024-12-16 15:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_setting_whatsapp_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Enter Title')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Enter Descriptions')),
                ('yt_video_url', models.URLField(blank=True, null=True, verbose_name='Enter Youtube video URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='AboutUs/', verbose_name='Select Image')),
            ],
        ),
    ]
