# Generated by Django 5.1.3 on 2024-11-23 09:20

import properties.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=properties.models.AutoSlugField(blank=True, editable=False, unique=True),
        ),
    ]
