# Generated by Django 5.1.3 on 2024-11-25 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_propertyimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Enter Descriptions'),
        ),
    ]
