# Generated by Django 5.1.3 on 2024-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='google_map_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enter Google map url'),
        ),
        migrations.AlterField(
            model_name='property',
            name='new_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Current price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Enter old price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='per_aana_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Per aana price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='plot_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Plot size'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_aana',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Total aana'),
        ),
        migrations.AlterField(
            model_name='property',
            name='yt_link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube link'),
        ),
    ]
