# Generated by Django 5.1.3 on 2024-11-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_category_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='land_area',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Land Area'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_face_direction',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Property Face Direction'),
        ),
        migrations.AddField(
            model_name='property',
            name='road_size',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Road size'),
        ),
        migrations.AddField(
            model_name='property',
            name='road_type',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Road Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_aana',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Total aana'),
        ),
    ]
