# Generated by Django 5.1.3 on 2024-11-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_land_area_property_property_face_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_face_direction',
            field=models.CharField(blank=True, choices=[('South', 'South'), ('East', 'East'), ('West', 'West'), ('North', 'North')], max_length=150, null=True, verbose_name='Choose Property Face Direction'),
        ),
    ]
