# Generated by Django 5.1.3 on 2024-11-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_property_property_face_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_trending',
        ),
        migrations.AddField(
            model_name='property',
            name='is_highlight',
            field=models.BooleanField(default=False, verbose_name='Is Highlight'),
        ),
    ]
