# Generated by Django 5.1.3 on 2024-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_remove_property_is_trending_property_is_highlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='parking_area',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Parking Area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Enter Address'),
        ),
    ]
